### PR TITLE
[WIP] update typescript, fix strict function types errors

### LINKED ISSUE #72: Compilation errors for typescript declarations
Declarations are failed to compile when used
`"strictFunctionTypes": true,` option in `tsconfig.json`.
As I know it enables bivariance checks for function types

```ts
function a(b: (c: string|number)=> string) {
  b(2)
}
a((b: string)=>b.concat('sd')) // compilation error with strictFnTypes enabled
```

### PR DESCRIPTION
**Pull request by goloveychuk**
With this pr you can compile with strictFunctionTypes enabled, with no error. 
In some places added `any`, trying to fix this.
fixes #72

### CODE REVIEW

**Comment by goloveychuk** [comment]
looks like the root problem of almost all errors is 
```ts

class A {
  cont!: () => keyof this
  
  prop!: string
}

class B extends A { 
  additionalProp!: string
}

let a: A = new B() // error

```
which is basically the same as 
```ts


class A {
  cont2!: () => 'prop'
  
  prop!: string
}

class B extends A {
  cont2: () => 'prop' | 'additionalProp' // forbidden extension
  
  additionalProp!: string
}

let a: A = new B()

```

**Comment by Pauan** [comment]
@goloveychuk Thanks a lot for this! I'll be doing a thorough code review soon.

**Comment by goloveychuk** [comment]
@Pauan  any news?

**Comment by rkovalyov** [comment]
@Pauan when u will be able to review, we a looking forward for this changes ?

**Comment by Pauan** [comment]
@goloveychuk @rkovalyov Yeah, sorry, I've been reviewing it, but it's slow going since it's a lot of changes (and I've had to work on some other things in the meantime).

**Comment by Pauan** [comment]
I've incorporated most of your changes, could you please rebase and resolve the conflicts?

Also, could you please make sure that it compiles successfully with TypeScript `2.8.1` (the oldest version we support)?

**Comment by Pauan** [comment]
Nevermind, I was able to fix the conflicts.

We use a different repo for our development, so I can't merge this as-is, but I incorporated your changes, and they will show up in the next release.

You have been given credit for your work. Thank you very much!

**Pull request closed without merging**
